name: check-and-deploy

on:
  push:
    branches: [ master ]

jobs:
  check:
    runs-on: ubuntu-latest
    name: check

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::devtools

      - name: Run devtools::check()
        run: devtools::check(
          args = c("--no-manual", "--as-cran"),
          error_on = "error")
        shell: Rscript {0}

  deploy:
    runs-on: ubuntu-latest
    needs: check
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            any::rsconnect

      - name: Deploy app to shinyapps.io
        env:
          SHINYAPPS_NAME: ${{ secrets.SHINYAPPS_NAME }}
          SHINYAPPS_ACCOUNT: ${{ secrets.SHINYAPPS_ACCOUNT }}
          SHINYAPPS_TOKEN: ${{ secrets.SHINYAPPS_TOKEN }}
          SHINYAPPS_SECRET: ${{ secrets.SHINYAPPS_SECRET }}
        run: |
          rsconnect::setAccountInfo(
            name   = Sys.getenv("SHINYAPPS_ACCOUNT"),
            token  = Sys.getenv("SHINYAPPS_TOKEN"),
            secret = Sys.getenv("SHINYAPPS_SECRET")
          )
          rsconnect::deployApp(appName = Sys.getenv("SHINYAPPS_NAME"))
        shell: Rscript {0}
